export default {
  data: [
    {
      title: 'My purpose was found in my wounds ✌🏾',
      authorName: 'Isaiah Dawe',
      id: 2218,
      slug: 'my-purpose-was-found-in-my-wounds',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/my-purpose-was-found-in-my-wounds.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/my-purpose-was-found-in-my-wounds',
      previewText: 'I know what it is like to feel hopeless, unworthy and be treated with disrespect – it’s something I would never wish upon another person. I want everyone to feel a sense of worth around me and to feel comfortable in who they truly are and a way I see myself encouraging this, is by being kind.   ',
      postDate: {
        date: '2018-11-04 15:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 25%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Isaiah_181104_044831.jpg',
        },
      ],
    },
    {
      title: 'I have a passion for people & kindness 😜',
      authorName: 'Lamarr Womble',
      id: 2207,
      slug: 'i-have-a-passion-for-people-kindness',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/i-have-a-passion-for-people-kindness.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/i-have-a-passion-for-people-kindness',
      previewText: 'It doesn’t seem hard to be a kind person, but we are products of our environments and experiences. Until we see what it means to be consistently kind, we may never know how it feels. I ask you all to continue to be an example of what it means to love and take care of people. You very well may change someone\'s life through your kindness!',
      postDate: {
        date: '2018-10-27 20:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: null,
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Lamarr_181027_090409.jpg',
        },
      ],
    },
    {
      title: 'Trekking a kindness trail 🚙',
      authorName: 'Shaun Edwards',
      id: 2191,
      slug: 'trekking-a-kindness-trail',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/trekking-a-kindness-trail.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/trekking-a-kindness-trail',
      previewText: 'When you are dropped in a Subaru outlander 15,979kms away from the sunny beaches of Sydney and instead are placed amongst the tall buildings of New York with the sole intention to fill a chartered plane which flies 200 US College students to Australia in four-months time without knowing a single soul; your instincts tell you kindness is going to be the only thing that gets you through the next month on the road.',
      postDate: {
        date: '2018-10-21 10:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 25%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Shauny-1.jpg',
        },
      ],
    },
    {
      title: 'A different future 👣',
      authorName: 'Bashir Yousufi',
      id: 2171,
      slug: 'a-different-future',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/a-different-future.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/a-different-future',
      previewText: 'My name is Bashir Yousufi. I am a proud new Australian of refugee background. I am part of the Hazara community found mostly in Afghanistan and Pakistan.',
      postDate: {
        date: '2018-10-04 16:01:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: null,
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Bashir.jpg',
        },
      ],
    },
    {
      title: 'A full extension of kindness ☺️🌱',
      authorName: 'Melati Wijsen',
      id: 2123,
      slug: 'a-full-extension-of-kindness',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/a-full-extension-of-kindness.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/a-full-extension-of-kindness',
      previewText: 'Having kindness at my core, I truly believe it will help me attract the right people, situations and opportunities onto my path. My hope is that with leading by example, my kindness extends to the person in front of me, next to me, the person reading these words, the person who listens to my talks will feel that ripple effect and want to express the same level of kindness they receive.',
      postDate: {
        date: '2018-09-29 22:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: null,
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/MELATIWIJSEN-by-Sharon-Angelia-0486.jpg',
        },
      ],
    },
    {
      title: 'Kindness in action 😉',
      authorName: 'Holley Murchison',
      id: 2106,
      slug: 'kindness-in-action',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/kindness-in-action.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/kindness-in-action',
      previewText: 'When you consider today’s social, economic, and political climate, the stories we tell about who we are and how we’re committed to impacting culture are more important than they’ve ever been. And that’s what I’m most excited about – working with people to uncover those stories to activate their potential for the greatest good.',
      postDate: {
        date: '2018-09-22 03:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 0%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/H.-Murchison-•-Bio-Photo.jpg',
        },
      ],
    },
    {
      title: 'Stitched with kindness 😊',
      authorName: 'Munjed Al Muderis',
      id: 2016,
      slug: 'stitched-with-kindness',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/stitched-with-kindness.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/stitched-with-kindness',
      previewText: 'Christmas Island is where I learnt the most valuable lesson of my life, the act of human kindness. I was asked to interpret for the Australian Federal Police while they intercepted a boat. One of the Deputies asked me, “when was the last time you spoke to your family?” I replied “just before I left Jakarta”. The Deputy told me that he was putting his job on the line, pulled out a satellite phone and asked me to sit on the ground. He told me to call my family.',
      postDate: {
        date: '2018-09-16 18:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 20%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Munjed.jpg',
        },
      ],
    },
    {
      title: 'Entitled to make a positive change ✊🏾🌷',
      authorName: 'Mercy Ngulube',
      id: 2004,
      slug: 'entitled-to-make-a-positive-change',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/entitled-to-make-a-positive-change.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/entitled-to-make-a-positive-change',
      previewText: 'I talk about the entitlement that is so often spoken of millennials. The one thing I love people feeling entitled to is the right to change their circumstances, for the better. So many of the problems we see in the world today come because of disregard of the simple ability to be kind, to care and to empathise. So many of the solutions we’ve seen in response to injustice, have come because people understand the importance of exercising their ability to change their circumstances.',
      postDate: {
        date: '2018-09-09 18:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 25%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Mercy-Profile.jpg',
        },
      ],
    },
    {
      title: 'A smile is the BEST gift 😄',
      authorName: 'Esther Kalenzi',
      id: 1987,
      slug: 'a-smile-is-the-best-gift',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/a-smile-is-the-best-gift.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/a-smile-is-the-best-gift',
      previewText: 'That weekend was a turning point for me. I had never felt so alive as I did spending time with these children and realising the opportunity we had to impact their lives. The next year, I decided to register 40 days over 40 smiles Foundation (4040) as a non-profit. Soon after, I quit my job in marketing and business development, to pursue this new dream, full time.',
      postDate: {
        date: '2018-09-02 18:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 20%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Esther.jpg',
        },
      ],
    },
    {
      title: 'AIME at Parliament House 🏠',
      authorName: 'Ben Abbatangelo',
      id: 1972,
      slug: 'aime-at-parliament-house',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/aime-at-parliament-house.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/aime-at-parliament-house',
      previewText: 'Australian politics dominated the conversation this week as we witnessed an all too familiar change in political leadership. The journalists smelt blood and relished at the opportunity, paying microscopic attention to the cracks and division within Parliament. The only story, and most compelling of them all, that is yet to be told is the one that I’m about to tell - and it’s a story that will one by one heal wounds, glue together cracks and knit the country back together.',
      postDate: {
        date: '2018-08-26 18:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/AIME-in-the-house.png',
        },
      ],
    },
    {
      title: 'Leaving tracks ♿⚡',
      authorName: 'Marcos Lopez',
      id: 1962,
      slug: 'leaving-tracks',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/leaving-tracks.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/leaving-tracks',
      previewText: 'I want to introduce you to my friend, Abel. A few years ago, he started the nonprofit, What Pushes You? and together, we are taking it worldwide. Recently, at the FIFA World Cup in Moscow, we saw a young guy who we thought could do with a new set of wheels. This is our story.',
      postDate: {
        date: '2018-08-19 18:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 53%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Marcos-Abel.jpg',
        },
      ],
    },
    {
      title: 'Kindness has no limits ✈️',
      authorName: 'Maya Ghazal',
      id: 1956,
      slug: 'kindness-has-no-limits',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/kindness-has-no-limits.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/kindness-has-no-limits',
      previewText: 'The idea of becoming a pilot is quite new for me because it didn’t cross my mind until last year when I decided it is what I want to do. It is cool to think that one day, I will be able to access any country and be respected because it is my job to fly people, and I am the same person who was not only turned away from school, but looked at as a burden by some countries.',
      postDate: {
        date: '2018-08-12 18:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 20%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Maya-Ghazal.-Pilot-in-training.jpg',
        },
      ],
    },
    {
      title: 'The power of kindness  ✊🏾✨',
      authorName: 'Khali Sweeney',
      id: 1945,
      slug: 'the-power-of-kindness',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/the-power-of-kindness.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/the-power-of-kindness',
      previewText: 'I’ve witnessed firsthand what kindness can do for those the world has written off, people who truly believe they’re not good enough, smart enough or strong enough to make it.',
      postDate: {
        date: '2018-08-05 18:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 35%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Khali-Head-Shot.jpg',
        },
      ],
    },
    {
      title: 'AIME’s FIRST African Australian Program Day 💪🏾🔥',
      authorName: 'Bem Ikyanyon',
      id: 1935,
      slug: 'aimes-first-african-australian-program-day',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/aimes-first-african-australian-program-day.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/aimes-first-african-australian-program-day',
      previewText: 'It was the start of flipping the script as African Australian kids take charge of the narrative.',
      postDate: {
        date: '2018-07-29 18:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 25%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/0O3A6534.jpg',
        },
      ],
    },
    {
      title: 'When strength met hope 🤘🏾🌷',
      authorName: 'Aminata Conteh-Biger',
      id: 1924,
      slug: 'when-strength-met-hope',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/when-strength-met-hope.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/when-strength-met-hope',
      previewText: 'My soul felt a sense of responsibility to do something about infant mortality in Sierra Leone. Every baby in the world deserves to be born healthy and in a stable environment, irrespective of their country of birth... This is a basic human right; it is just that simple.',
      postDate: {
        date: '2018-07-22 18:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 15%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/When-strength-met-hope.jpg',
        },
      ],
    },
    {
      title: 'Kindness from a classroom in Brazil 📚',
      authorName: 'Bruno Paiva',
      id: 1890,
      slug: 'kindness-from-a-classroom-in-brazil',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/kindness-from-a-classroom-in-brazil.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/kindness-from-a-classroom-in-brazil',
      previewText: 'I could not be gifted with greater honor than knowing that thousands of people across the globe are coming back to believing in love for others in the importance of affection thanks to what I have experienced.',
      postDate: {
        date: '2018-07-15 18:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 21%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Screen-Shot-2018-07-09-at-12.11.45-PM.png',
        },
      ],
    },
    {
      title: 'Because of her, we can 💃🏾',
      authorName: 'Rona Glynn-McDonald',
      id: 1880,
      slug: 'because-of-her-we-can',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/because-of-her-we-can.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/because-of-her-we-can',
      previewText: 'I share this knowledge as an act of kindness, because people can’t grow unless we are open to sharing. I share this knowledge to allow people to take a proactive step in displaying kindness and empathy for other cultures.',
      postDate: {
        date: '2018-07-08 18:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: null,
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Screen-Shot-2018-07-03-at-12.07.43-PM.png',
        },
      ],
    },
    {
      title: 'Tales of an adventuring soul 🌍❤️',
      authorName: 'Agustin Di Gennaro',
      id: 1586,
      slug: 'sunday-kindness-tales-of-an-adventuring-soul-️',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/sunday-kindness-tales-of-an-adventuring-soul-️.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/sunday-kindness-tales-of-an-adventuring-soul-️',
      previewText: 'I know I am only a dude with a backpack and ain’t changing anything in the world but this story is not about me after all, it has a purpose of giving you the courage and motivation to discover new places, visit exciting landspaces and even more important; meet fantastic people and find what we do have in common despite of our clear differences.',
      postDate: {
        date: '2018-07-01 18:30:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 20%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Screen-Shot-2018-06-25-at-10.22.14-AM.png',
        },
      ],
    },
    {
      title: 'Changing the world one brushstroke at a time. 🎨',
      authorName: 'Rouble Nagi',
      id: 1644,
      slug: 'sunday-kindness-changing-the-world-one-brushstroke-at-a-time-1',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/sunday-kindness-changing-the-world-one-brushstroke-at-a-time-1.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/sunday-kindness-changing-the-world-one-brushstroke-at-a-time-1',
      previewText: 'Art means a lot to me, but it’s no longer everything. Today it\'s all about the people I work for, empowering women living in the slums giving them ambition and strength; courage and resilience. It’s all about “paying it forward.”',
      postDate: {
        date: '2018-06-24 10:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 20%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/DSC_7204.JPG',
        },
      ],
    },
    {
      title: 'I believe in looking past perceptions & fearlessly shining positivity 🦁',
      authorName: 'Eliza Di Mauro',
      id: 1665,
      slug: 'sunday-kindness-looking-past-perceptions-fearlessly-shining-positivity-1',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/sunday-kindness-looking-past-perceptions-fearlessly-shining-positivity-1.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/sunday-kindness-looking-past-perceptions-fearlessly-shining-positivity-1',
      previewText: 'It’s hard to put into words the rippling positive effect that night had, seeing an overwhelming pride fill the entire choir like a breath of pure oxygen, a wave of confidence and audience recognition transforming their posture and grinning faces into pure joy – it’s transformative.',
      postDate: {
        date: '2018-06-17 00:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: null,
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/IMG_3014.jpg',
        },
      ],
    },
    {
      title: 'Be kind to each other, Darlings 😘',
      authorName: 'Deborah Kirby-Parsons',
      id: 1688,
      slug: 'sunday-kindness-be-kind-to-each-other-darlings',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/sunday-kindness-be-kind-to-each-other-darlings.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/sunday-kindness-be-kind-to-each-other-darlings',
      previewText: 'Emotion is a funny thing and it seems to have been holding my heart, very tightly, my entire life: "Deb, you are too soft," "...such a sook," "...overly sensitive." It’s who I am, so I guess it comes as no surprise that at our recent Annual General Meeting, I was once again grabbed by that emotional squeezing.',
      postDate: {
        date: '2018-06-10 15:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 20%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Screen-Shot-2018-06-07-at-4.37.55-PM.png',
        },
      ],
    },
    {
      title: 'There is kindness in trust 💫',
      authorName: 'Xavier Masson-Leach',
      id: 1704,
      slug: 'sunday-kindness-there-is-kindness-in-trust',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/sunday-kindness-there-is-kindness-in-trust.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/sunday-kindness-there-is-kindness-in-trust',
      previewText: 'The most important aspect of trust: it lets you see the world in a new way.',
      postDate: {
        date: '2018-06-03 16:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Screen-Shot-2018-06-28-at-3.47.35-PM.png',
        },
      ],
    },
    {
      title: 'I believe in kindness and free coffee 😜',
      authorName: 'Pej',
      id: 1759,
      slug: 'sunday-kindness-i-believe-in-kindness-and-free-coffee',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/sunday-kindness-i-believe-in-kindness-and-free-coffee.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/sunday-kindness-i-believe-in-kindness-and-free-coffee',
      previewText: 'Kindness costs nothing - other than your time which is more valuable than anything else. Such a simple act can make a huge difference for someone\'s week, month or year.',
      postDate: {
        date: '2018-05-20 00:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: true,
      bannerBackgroundPosition: null,
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Screen-Shot-2018-06-28-at-4.11.45-PM.png',
        },
      ],
    },
    {
      title: 'Wherever there is a human being, there is an opportunity for kindness 💃🏻',
      authorName: 'Superheroes of kindness',
      id: 1743,
      slug: 'sunday-kindness-wherever-there-is-a-human-being-there-is-an-opportunity-for-kindness',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/sunday-kindness-wherever-there-is-a-human-being-there-is-an-opportunity-for-kindness.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/sunday-kindness-wherever-there-is-a-human-being-there-is-an-opportunity-for-kindness',
      previewText: 'We asked a small group of humans to write how they would commit to kindness, here is the wisdom we unlocked',
      postDate: {
        date: '2018-05-13 00:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '0% 80%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Screen-Shot-2018-06-28-at-4.51.20-PM.png',
        },
      ],
    },
    {
      title: 'What happens when kindness spreads like wildflowers? 🌸',
      authorName: 'Kindness deliverers',
      id: 1838,
      slug: 'sunday-kindness-what-happens-when-kindness-spreads-like-wildflowers',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/sunday-kindness-what-happens-when-kindness-spreads-like-wildflowers.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/sunday-kindness-what-happens-when-kindness-spreads-like-wildflowers',
      previewText: 'It turns out simple acts create big impact. Here\'s how a $50 note sparked a movement of kindness around the world.',
      postDate: {
        date: '2018-05-06 00:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: null,
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Screen-Shot-2018-06-28-at-7.11.01-PM_180628_094509.png',
        },
      ],
    },
    {
      title: 'Making the invisible visible 🙌🏾🌻',
      authorName: 'Jody Barney',
      id: 1541,
      slug: 'sunday-kindness-46',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/sunday-kindness-46.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/sunday-kindness-46',
      previewText: 'I am Jody Barney. I am a Birri-Gubba/Urangan woman from South East Queensland. I am Aboriginal, I am Deaf, I am gay, and currently I am living in rural Victoria Australia. I’m not yet 50, but I have been doing my work for exactly 30 years.',
      postDate: {
        date: '2018-03-25 00:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: null,
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Sunday-copy.png',
        },
      ],
    },
    {
      title: 'Mentoring, key to a fairer world 🔑',
      authorName: 'Kabir Dhanji',
      id: 1528,
      slug: 'sunday-kindness-45',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/sunday-kindness-45.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/sunday-kindness-45',
      previewText: '“Sunday Kindness” has an established beginning that is this week forfeit, because there’s no sense in conventional beginnings; they are always shifting moments that hold still long enough for a breath, and then they’re something else, so there is no correct way for things to begin.',
      postDate: {
        date: '2018-03-18 00:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: '25%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Kabir-2.jpg',
        },
      ],
    },
    {
      title: 'Forgiveness liberates the soul 🌿',
      authorName: 'Candice Mama',
      id: 1519,
      slug: 'sunday-kindness-44',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/sunday-kindness-44.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/sunday-kindness-44',
      previewText: 'My name is Candice Mama, I was born in 1991 in South Africa; a country that was gripped by the grossly violent and oppressive system of Apartheid and this is my story.',
      postDate: {
        date: '2018-03-11 00:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: null,
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Sunday-copy-4.png',
        },
      ],
    },
    {
      title: 'Trust & human kindness. The fundamental currencies. 🙏🏾🦄',
      authorName: 'Ben Abbatangelo',
      id: 1481,
      slug: 'sunday-kindness-43',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/sunday-kindness-43.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/sunday-kindness-43',
      previewText: 'AIME Family, my name is Ben Abbatangelo and I’m the Deputy CEO at AIME. I’m penning this note as I tackle the last leg of what has been an immensely rich 10 days in Africa.',
      postDate: {
        date: '2018-03-05 14:16:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: true,
      bannerBackgroundPosition: '0% 30%',
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/untitled-4.jpg',
        },
      ],
    },
    {
      title: 'Apparel Pop Up Stores for Hottest 100',
      authorName: 'Beth Zucker',
      id: 1513,
      slug: 'apparel-pop-up-stores-for-hottest-100',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/apparel-pop-up-stores-for-hottest-100.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/apparel-pop-up-stores-for-hottest-100',
      previewText: 'Missed out on ordering a Hottest 100 tee in time for the 27th? Don\'t sweat it. We got ya back! We\'re running one-off pop up stores at locations around Aus so you\'ll be counting down your favourite tunes in style and supporting AIME.',
      postDate: {
        date: '2018-01-24 09:58:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: null,
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/Apparel-Hats.jpg',
        },
      ],
    },
    {
      title: 'The Backdrop to AIME',
      authorName: 'Jack Manning Bancroft',
      id: 2028,
      slug: 'the-backdrop-to-aime',
      jsonUrl: 'https://aimeweb-backend-production.herokuapp.com/api/stories/the-backdrop-to-aime.json',
      url: 'https://aimeweb-backend-production.herokuapp.com/story/the-backdrop-to-aime',
      previewText: 'Aboriginal and Torres Strait Islander people, the two Indigenous groups in Australia, were invaded by the British in 1788.',
      postDate: {
        date: '2017-02-26 00:00:00.000000',
        timezone_type: 3,
        timezone: 'Australia/Sydney',
      },
      isFeatured: false,
      bannerBackgroundPosition: null,
      bannerImage: [
        {
          image: 'https://d2ylaz7bdw65jx.cloudfront.net/resources/28454321836_c40058e602_k.jpg',
        },
      ],
    },
  ],
  meta: {
    pagination: {
      total: 31,
      count: 31,
      per_page: 100,
      current_page: 1,
      total_pages: 1,
      links: [],
    },
  },
};
