# Specify audits to run. Also include any plugins (like axe)
 audits:
     - axe
     - size
     - lighthouse
     - heap-snapshot
     - unused-source

 configs:
   comment:
     # Only show failures in GitHub PR comments.
     # Useful to pinpoint why a build has failed
     onlyFailures: true

   # Heap snapshot settings
   heap-snapshot:
     threshold:
       Documents: 11
       Frames: 5
       JSHeapTotalSize: 13356000
       JSHeapUsedSize: 10068000
       Nodes: 800
       RecalcStyleCount: 15
       LayoutCount: 15

   # Lighthouse settings
   lighthouse:
     skipAudits:
       - uses-http2
       - redirects-http
       - uses-long-cache-ttl
       - uses-text-compression
     outputHtml: ./gimbal-artifacts/lighthouse.html
     threshold:
       accessibility: 95
       "best-practices": 95
       performance: 95
       pwa: 95
       seo: 95

   # File and directory size settings
   size:
     - path: ./build/precache-*.js
       maxSize: 10 KB
     - path: ./build/static/js/[0-9]*.chunk.js
       maxSize: 1 MB
     - path: ./build/static/js/*.chunk.js
       maxSize: 1 MB
     - path: ./build/static/js/runtime*.js
       maxSize: 10 KB
     - path: ./build/index.html
       maxSize: 10 KB
     - path: ./build/favicon.ico
       maxSize: 10 KB
     - path: ./build/
       maxSize: 18 MB

   # Unused source settings
   unused-source:
     threshold:
       - path: "**/*(private).*.chunk.css"
         maxSize: 60%
       - path: "**/!(private).*.chunk.css"
         maxSize: 60%
       - path: "**/*([0-9]).*.chunk.js"
         maxSize: 90%
       - path: "**/!([0-9]|main).*.chunk.js"
         maxSize: 45%
       - path: "**/(main).*.chunk.js"
         maxSize: 50%

 # Locations of reports. Useful for storing artifacts in CI
 outputs:
   # Only show failures in CLI
   cli:
     onlyFailures: true
   html: ./gimbal-artifacts/results.html
   json: ./gimbal-artifacts/results.json
   markdown: ./gimbal-artifacts/results.md

 # Plugins
 plugins:
   # Compare metrics to last-saved values
   - plugin: "@modus/gimbal-plugin-last-value"
     saveOnlyOnSuccess: false

   # Save reports to a database. Needed for gimbal-plugin-last-value
   - plugin: "@modus/gimbal-plugin-sqlite"
     lastValue: true

   # Axe a11y audits
   - plugin: "@modus/gimbal-plugin-axe"
     thresholds:
       aria-allowed-attr: critical
       color-contrast: serious
       landmark-one-main: moderate
       landmark-complementary-is-top-level: moderate
       meta-viewport: critical
       region: moderate
       page-has-heading-one: moderate
       scrollable-region-focusable: moderate
