sudo: false
language: node_js
node_js:
- '12'
install:
- node -v
before_script:
- yarn
cache:
  directories:
  - node_modules
  yarn: true
git:
  depth: 3
script:
  - yarn build
after_success:
  - sleep 4m
  - yarn run lhbot https://website-$TRAVIS_PULL_REQUEST.herokuapp.com/