---
sudo: false
language: node_js
node_js:
- "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - node -v
before_script:
  - yarn
cache:
  directories:
    - node_modules
  yarn: true

git:
  depth: 3

script:
  - npm run build
  - npm run lint
  - npm run test
  - sleep 3
  - npm run test:lighthouse:ci

jobs:
  include:
    - stage: Peformance reporter
      if: type = pull_request
      env:
        - NODE_ENV=production
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: app-name
  on:
    repo: master/website-ssr-blueprint-poc
after_success:
  - yarn run lhbot -- https://staging.example.com
  - yarn run lhbot -- https://master.example.com
     