sudo: false
language: node_js
node_js:
- '10'
install:
- node -v
before_script:
- yarn
cache:
  directories:
  - node_modules
  yarn: true
git:
  depth: 3
script:
  - yarn build
after_success:
  - sleep 5m
  - yarn run lhbot https://website-ssr.herokuapp.com/