sudo: false
language: node_js
node_js:
- '10'
install:
- node -v
before_script:
- yarn
cache:
  directories:
  - node_modules
  yarn: true
git:
  depth: 3
env:
  - GENERATE_SOURCEMAP=false
script:
  - yarn build
after_success:
  - sleep 4m
  - yarn run lhbot https://website-ssr-pr-$TRAVIS_PULL_REQUEST.herokuapp.com/