sudo: false
language: node_js
node_js:
- '10'
install:
- node -v
before_script:
- yarn
cache:
  directories:
  - node_modules
  yarn: true
git:
  depth: 3
script:
- yarn build
#jobs:
#  include:
#  - stage: Peformance reporter
#    script: skip
#    deploy:
#      provider: s3
#      access_key_id: "YOUR AWS ACCESS KEY"
#      secret_access_key: "YOUR AWS SECRET KEY"
#      bucket: "S3 Bucket"
after_success:
  - sleep 3
  - yarn run lhbot https://website-ssr.herokuapp.com/