name: CI

on:
  push:
    branches:
    - staging
  pull_request:
    branches:
    - staging

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install yarn dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Upload to aws
        run: yarn sync:aws:next:staging
