name: Pull Request Deploy
on:
  pull_request:
    branches:
      - staging
      - master
jobs:
  gimbal:
    runs-on: ubuntu-latest
    steps:
      - name: Performance Budgeting Regression Testing
        uses: ModusCreateOrg/gimbal/action@master
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}