name: Gimbal
on:
  pull_request:
    branches:
      - staging
      - master
      
env:
  REACT_APP_BUGSNAG_KEY: ${{ secrets.REACT_APP_BUGSNAG_KEY }}
  REACT_APP_PRO_IP_KEY: ${{ secrets.REACT_APP_PRO_IP_KEY }}
  REACT_APP_AIRTABLE_API_KEY: ${{ secrets.REACT_APP_AIRTABLE_API_KEY }}
  REACT_APP_CONTENTFUL_ENTRY_KEY_REDIRECTS: ${{ secrets.REACT_APP_CONTENTFUL_ENTRY_KEY_REDIRECTS }}
  REACT_APP_CONTENTFUL_ENTRY_KEY_STORIES: ${{ secrets.REACT_APP_CONTENTFUL_ENTRY_KEY_STORIES }}
  REACT_APP_CONTENTFUL_API_KEY: ${{ secrets.REACT_APP_CONTENTFUL_API_KEY }}
  REACT_APP_FILE_UPLOADER_API_KEY: ${{ secrets.REACT_APP_FILE_UPLOADER_API_KEY }}
  REACT_APP_ASSETS_URL: https://d1muvgoqe3g8vw.cloudfront.net/website
  REACT_APP_CRAFT_API: https://aimeweb-backend-staging.herokuapp.com/
  REACT_APP_HOST_ENV: staging
  REACT_APP_PORTAL_API: https://aime-portal-api-staging.herokuapp.com
  REACT_APP_THEME: rainbow
  REACT_APP_INTERCOM_APP_ID: g36n1wzq
  REACT_APP_SHOPIFY_STORE_FRONT_ACCESS_TOKEN: 560dd7f8110349a17d6e96c46d02a0ce
  REACT_APP_SHOPIFY_DOMAIN: aimementoring.myshopify.com
  REACT_APP_DONATE_USERNAME: website@aimementoring.com
  REACT_APP_DONATE_PASSWORD: ***REMOVED***
  REACT_APP_DONATE_ORGANISATION_UUID: 7eafc9b2-404f-11e7-bc97-06facaa3db7b
  REACT_APP_AIRTABLE_STAFF_RECRUITMENT_BASE: appiTNzrkMrckYbqk
  REACT_APP_PITCH_YOURSELF_TO_AIME_ID: rec8N1DIykET8T9SF
  REACT_APP_CONTENTFUL_SPACE_ID: iz0aikshgysc
  REACT_APP_CONTENTFUL_CONTENT_TYPE_REDIRECTS: redirectEntries
  REACT_APP_CONTENTFUL_CONTENT_TYPE_STORIES: post
  REACT_APP_GOOGLE_TAG_MANAGER: GTM-NK5SFHW
  REACT_APP_CDN_ROOT: https://d2ylaz7bdw65jx.cloudfront.net
  REACT_APP_CONTENTFUL_API_ENVIRONMENT: master

jobs:
  gimbal:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install npm dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Performance Budgeting Regression Testing
        uses: ModusCreateOrg/gimbal/action@master
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}